before:
  hooks:
    - go mod download

builds:
- id: device-portal
  main: ./cmd/deviceportal
  binary: device-portal
  env:
    - CGO_ENABLED=0
  targets:
    - linux_amd64_v1
    - linux_arm64
    - linux_arm_7
    # - darwin_amd64_v1
    # - darwin_arm64
    # - windows_amd64_v1

archives:
  - id: device-portal
    builds: ["device-portal"]
    name_template: "device-portal_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip

changelog:
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 10
    - title: Builds
      regexp: '^.*?build(\([[:word:]]+\))??!?:.+$'
      order: 20
    - title: etc
      order: 30
  filters:
    exclude:
      - '^.*?chore(\([[:word:]]+\))??!?:.+$'
      - '^.*?docs(\([[:word:]]+\))??!?:.+$'
      - '^.*?test(\([[:word:]]+\))??!?:.+$'
      - '^.*?ci(\([[:word:]]+\))??!?:.+$'

release:
  prerelease: auto
  footer: |
    **Full hand-crafted changelog**: [`CHANGELOG.md`]({{ .GitURL }}/blob/main/CHANGELOG.md)

    {{ if and .Tag .PreviousTag }}
      **Commit history**: [{{ .PreviousTag }}...{{ .Tag }}]({{ .GitURL }}/compare/{{ .Tag }}...{{ .PreviousTag }})
    {{ else if .PreviousTag }}
      **Commit history**: [{{ .PreviousTag }}...{{ .ShortCommit }}]({{ .GitURL }}/compare/{{ .Commit }}...{{ .PreviousTag }})
    {{ end }}

dockers:
  # device-portal
  - id: device-portal-amd64
    ids:
      - device-portal
    dockerfile: "Dockerfile"
    use: buildx
    image_templates:
    - "ghcr.io/planktoscope/device-portal:latest-amd64"
    - "ghcr.io/planktoscope/device-portal:{{ .Major }}-amd64"
    - "ghcr.io/planktoscope/device-portal:{{ .Major }}.{{ .Minor }}-amd64"
    - "ghcr.io/planktoscope/device-portal:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
    build_flag_templates:
    - "--pull"
    - "--platform=linux/amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--label=org.opencontainers.image.licenses=(Apache-2.0 OR BlueOak-1.0.0)"
  - id: device-portal-arm64v8
    ids:
      - device-portal
    dockerfile: "Dockerfile"
    use: buildx
    goarch: arm64
    image_templates:
    - "ghcr.io/planktoscope/device-portal:latest-arm64v8"
    - "ghcr.io/planktoscope/device-portal:{{ .Major }}-arm64v8"
    - "ghcr.io/planktoscope/device-portal:{{ .Major }}.{{ .Minor }}-arm64v8"
    - "ghcr.io/planktoscope/device-portal:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8"
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm64/v8"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--label=org.opencontainers.image.licenses=(Apache-2.0 OR BlueOak-1.0.0)"
  - id: device-portal-armv7
    ids:
      - device-portal
    dockerfile: "Dockerfile"
    use: buildx
    goarch: arm
    goarm: 7
    image_templates:
    - "ghcr.io/planktoscope/device-portal:latest-armv7"
    - "ghcr.io/planktoscope/device-portal:{{ .Major }}-armv7"
    - "ghcr.io/planktoscope/device-portal:{{ .Major }}.{{ .Minor }}-armv7"
    - "ghcr.io/planktoscope/device-portal:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-armv7"
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm/v7"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--label=org.opencontainers.image.licenses=(Apache-2.0 OR BlueOak-1.0.0)"

docker_manifests:
  # device-portal
  - name_template: "ghcr.io/planktoscope/device-portal:latest"
    image_templates:
      - "ghcr.io/planktoscope/device-portal:latest-amd64"
      - "ghcr.io/planktoscope/device-portal:latest-arm64v8"
      - "ghcr.io/planktoscope/device-portal:latest-armv7"
  - name_template: "ghcr.io/planktoscope/device-portal:{{ .Major }}"
    image_templates:
      - "ghcr.io/planktoscope/device-portal:{{ .Major }}-amd64"
      - "ghcr.io/planktoscope/device-portal:{{ .Major }}-arm64v8"
      - "ghcr.io/planktoscope/device-portal:{{ .Major }}-armv7"
  - name_template: "ghcr.io/planktoscope/device-portal:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/planktoscope/device-portal:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/planktoscope/device-portal:{{ .Major }}.{{ .Minor }}-arm64v8"
      - "ghcr.io/planktoscope/device-portal:{{ .Major }}.{{ .Minor }}-armv7"
  - name_template: "ghcr.io/planktoscope/device-portal:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    image_templates:
      - "ghcr.io/planktoscope/device-portal:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "ghcr.io/planktoscope/device-portal:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8"
      - "ghcr.io/planktoscope/device-portal:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-armv7"
