version: 2

gomod:
  proxy: true
before:
  hooks:
    - go mod download

builds:
- id: device-portal
  main: ./cmd/deviceportal
  binary: device-portal
  mod_timestamp: "{{ .CommitTimestamp }}"
  flags:
    - -trimpath
  ldflags:
    - -w
    - -X main.buildSummary={{ .Summary }}
    - -X main.buildVersion={{ .Version }}
    - -X main.buildCommitFull={{ .FullCommit }}
    - -X main.buildCommitShort={{ .ShortCommit }}
    - -X main.buildCommitDate={{ .CommitDate }}
    - -X main.buildCommitTimestamp={{ .CommitTimestamp }}
    - -X main.buildReleaseURL={{ .ReleaseURL }}
    - -X main.buildRepo={{ .GitURL }}
    - -X main.buildSystem=goreleaser
  env:
    - CGO_ENABLED=0
  targets:
    - linux_amd64_v1
    - linux_arm64
    # - darwin_amd64_v1
    # - darwin_arm64
    # - windows_amd64_v1
  hooks:
    pre: make buildweb

archives:
  - id: device-portal
    ids: ["device-portal"]
    name_template: "device-portal_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - 'LICENSE*'
      - 'README*'
      - 'CHANGELOG*'
      - 'license*'
      - 'readme*'
      - 'changelog*'
      - 'web/templates/**'

changelog:
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 10
    - title: Builds
      regexp: '^.*?build(\([[:word:]]+\))??!?:.+$'
      order: 20
    - title: etc
      order: 30
  filters:
    exclude:
      - '^.*?chore(\([[:word:]]+\))??!?:.+$'
      - '^.*?docs(\([[:word:]]+\))??!?:.+$'
      - '^.*?test(\([[:word:]]+\))??!?:.+$'
      - '^.*?ci(\([[:word:]]+\))??!?:.+$'

release:
  prerelease: auto
  footer: |
    {{ if and .Tag .PreviousTag -}}
      **Commit history**: [{{ .PreviousTag }}...{{ .Tag }}]({{ .GitURL }}/compare/{{ .Tag }}...{{ .PreviousTag }})
    {{- else if .PreviousTag- }}
      **Commit history**: [{{ .PreviousTag }}...{{ .ShortCommit }}]({{ .GitURL }}/compare/{{ .Commit }}...{{ .PreviousTag }})
    {{- end }}

dockers:
  # device-portal
  - id: device-portal-amd64
    ids:
      - device-portal
    dockerfile: "Dockerfile"
    use: buildx
    image_templates:
      - "ghcr.io/openuc2/device-portal:latest-amd64"
      - "ghcr.io/openuc2/device-portal:{{ .Major }}-amd64"
      - "ghcr.io/openuc2/device-portal:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/openuc2/device-portal:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.licenses=(Apache-2.0 OR BlueOak-1.0.0)"
    extra_files:
      - "web/templates"
  - id: device-portal-arm64v8
    ids:
      - device-portal
    dockerfile: "Dockerfile"
    use: buildx
    goarch: arm64
    image_templates:
      - "ghcr.io/openuc2/device-portal:latest-arm64v8"
      - "ghcr.io/openuc2/device-portal:{{ .Major }}-arm64v8"
      - "ghcr.io/openuc2/device-portal:{{ .Major }}.{{ .Minor }}-arm64v8"
      - "ghcr.io/openuc2/device-portal:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.licenses=(Apache-2.0 OR BlueOak-1.0.0)"
    extra_files:
      - "web/templates"

docker_manifests:
  # device-portal
  - name_template: "ghcr.io/openuc2/device-portal:latest"
    image_templates:
      - "ghcr.io/openuc2/device-portal:latest-amd64"
      - "ghcr.io/openuc2/device-portal:latest-arm64v8"
  - name_template: "ghcr.io/openuc2/device-portal:{{ .Major }}"
    image_templates:
      - "ghcr.io/openuc2/device-portal:{{ .Major }}-amd64"
      - "ghcr.io/openuc2/device-portal:{{ .Major }}-arm64v8"
  - name_template: "ghcr.io/openuc2/device-portal:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/openuc2/device-portal:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/openuc2/device-portal:{{ .Major }}.{{ .Minor }}-arm64v8"
  - name_template: "ghcr.io/openuc2/device-portal:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    image_templates:
      - "ghcr.io/openuc2/device-portal:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"
      - "ghcr.io/openuc2/device-portal:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64v8"
